### ISSUE TITLE
Myrecon.py Error

### ISSUE THREAD

**Issue by secfb** [gwen001/myrecon.py#2]
OS=Kali Linux 5.3 Kernel
### Is this tool not yet completed? When i scan it i get the following error.
<img width="1208" alt="aa" src="https://user-images.githubusercontent.com/38748801/74816479-4e80d380-530c-11ea-95df-c8c5269578d9.png">

**Comment by attacker34** [comment]
Hi @gwen001  Please look at this issue..I am getting same issue.

**Comment by gwen001** [comment]
This error occurs because myrecon.py isn't in your executable path.

Perhaps you could create a symlink, something like:
```
ln -s $(pwd)/myrecon.py /usr/local/bin/
```

But if you have that problem with this script you'll get the same for all others scripts used in there: crlf.py, cors.py, smuggler.py and so on....

**Comment by attacker34** [comment]
Hi @gwen001 Sorry, but its not working. I have tried to create symlink as suggested by you.. Even findomain not worked in start by doing that.
 
I've even tried to symlink entire folder of myrecon.py but its still not working. When I symlinked all folder it started working but again i got same error. 

```
[*] ./waybackurls example.com true /root/myrecon/raw_wayback 2>&1 >/dev/null &
[+] 0 endpoints found.
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found
sh: 1: myrecon.py: not found

```

And yes. Other tools like smuggler.py, cors.py etc are also not working as you pointed out above.

**Comment by gwen001** [comment]
So you have to find a way on your system to add those binaries executable by themself. Check your path maybe ?

This must have to work:
```
$ myrecon.py .....
```

**Comment by nk9** [comment]
Indeed, you need to download the [pentest-tools repo](https://github.com/gwen001/pentest-tools) and add it to your path.

**Comment by Fawadkhanfk** [comment]
i am facing the same issue can you help me with this P

**Comment by nk9** [comment]
Is the pentest-tools repo in your path? Have you opened a new terminal since adding it?

**Comment by gwen001** [comment]
Sorry, abandoned project.

But since many peoples encounter the same problem: all `.py` must be in your executable path.
