### ISSUE TITLE
Error no file or directory found.

### ISSUE THREAD

**Issue by KathanP19** [gwen001/myrecon.py#5]
ec2-user@kali:~/myrecon.py$ python3 myrecon.py -d hyatt.com -o hyatt
[+] output directory is: hyatt
[+] 1 domains found.
[+] saved in hyatt/domains
[+] looking for subdomains...
[*] findomain -t hyatt.com
[+] 3016 hosts found.
[+] saved in hyatt/hosts
[+] resolving...
[+] 301 ips found.6
[+] saved in hyatt/ips
[+] 2759 hosts alive found
[+] 16 dead hosts found, cleaning...
[+] creating urls...
[+] looking for endpoints...
[*] github-endpoints.py -d hyatt.com -s | tee -a raw_github-endpoints endpoints_grabbed 2>&1 >/dev/null &
[*] google-search.py -b -d -e 100 -t "site:hyatt.com" | tee -a raw_google-domain endpoints_grabbed 2>&1 >/dev/null &
[*] google-search.py -b -d -e 100 -t "site:hyatt.com inurl:&" | tee -a raw_google-domain endpoints_grabbed 2>&1 >/dev/null &
[*] waybackurls hyatt.com true /home/ec2-user/myrecon.py/raw_wayback 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: 'hyatt/urls_hosts'
ec2-user@kali:~/myrecon.py$ [+] output directory is: /home/ec2-user/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/ec2-user/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/ec2-user/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: subto
[*] subjack -a -t 50 -timeout 20 -ssl -c "/opt/SecLists/mine/subjack_fingerprints.json" -v -w "/home/ec2-user/myrecon.py/hosts" -o "subto/output" 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: screenshot
[*] cat "/home/ec2-user/myrecon.py/urls" | aquatone -out screenshot 2>&1 >/dev/null &
[+] output directory is: /home/ec2-user/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/ec2-user/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/ec2-user/myrecon.py
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: xss
[*] xss.py -t 10 -n "/usr/local/bin/phantomjs" -p "/opt/SecLists/mine/xss-myshort.txt" -u "/home/ec2-user/myrecon.py/endpoints" 2>&1 >/dev/null &
sh: 1: subjack: not found
cat: /home/ec2-user/myrecon.py/urls: No such file or directory
sh: 1: aquatone: not found
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: cors
[*] cors.py -t 100 -u "/home/ec2-user/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: crlf
[*] crlf.py -t 200 -u "/home/ec2-user/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[+] resume session, loading datas...
[+] output directory is: /home/ec2-user/myrecon.py
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: openredirect
[*] openredirect.py -t 100 -u "/home/ec2-user/myrecon.py/endpoints" 2>&1 >/dev/null &
[+] resume session, loading datas...
[+] output directory is: /home/ec2-user/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: smuggling
[*] smuggler.py -v 0 -t 50 -u "/home/ec2-user/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: quickhits
[*] ffuf -u HFUZZ/WFUZZ -w "/home/ec2-user/myrecon.py/urls":HFUZZ -w "/opt/SecLists/mine/myhardw.txt":WFUZZ -o raw_quickhits 2>&1 >/dev/null &
[+] output directory is: /home/ec2-user/myrecon.py
[+] resume session, loading datas...
sh: 1: ffuf: not found
[-] error occurred: [Errno 2] No such file or directory: '/home/ec2-user/myrecon.py/domains'
[+] running mod: googledorks
[-] file not found: /opt/SecLists/mine/gg-dorks.txt
usage: xss.py [-h] [-a PATH] [-c COOKIES] [-n PHANTOM] [-o HOSTS]
              [-p PAYLOADS] [-s SCHEME] [-t THREADS] [-u URLS] [-v VERBOSE]
xss.py: error: phantomjs not found!

**Comment by KathanP19** [comment]
i tried to run in home as well in myrecon dir same error i had also install phantomjs still same.

**Comment by gwen001** [comment]
```sh: 1: ffuf: not found```
Install ffuf

```sh: 1: subjack: not found```
Install subjack

```sh: 1: aquatone: not found```
Install aquatone

**Comment by KathanP19** [comment]
thanks ffuf was installed and subjack too but aquatone.
