### ISSUE TITLE
No Such File or Directory Error If used -o function

### ISSUE THREAD

**Issue by KathanP19** [gwen001/myrecon.py#6]
python3 myrecon.py -d hyatt.com -o hyatt
[+] output directory is: hyatt
[+] 1 domains found.
[+] saved in hyatt/domains
[+] looking for subdomains...
[*] assetfinder -subs-only hyatt.com
[+] 834 hosts found.
[+] saved in hyatt/hosts
[+] resolving...
[+] 241 ips found.
[+] saved in hyatt/ips
[+] 721 hosts alive found
[+] 12 dead hosts found, cleaning...
[+] creating urls...
[+] looking for endpoints...
[*] github-endpoints.py -d hyatt.com -s | tee -a raw_github-endpoints endpoints_grabbed 2>&1 >/dev/null &
[*] google-search.py -b -d -e 100 -t "site:hyatt.com" | tee -a raw_google-domain endpoints_grabbed 2>&1 >/dev/null &
[*] google-search.py -b -d -e 100 -t "site:hyatt.com inurl:&" | tee -a raw_google-domain endpoints_grabbed 2>&1 >/dev/null &
[*] waybackurls hyatt.com true /home/natsu/Desktop/Tools/myrecon.py/raw_wayback 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: 'hyatt/urls_hosts'
┌─[natsu@parrot]─[~/Desktop/Tools/myrecon.py]
└──╼ $[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: screenshot
[*] cat "/home/natsu/Desktop/Tools/myrecon.py/urls" | aquatone -out screenshot 2>&1 >/dev/null &
cat: /home/natsu/Desktop/Tools/myrecon.py/urls: No such file or directory
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: subto
[*] subjack -a -t 50 -timeout 20 -ssl -c "/opt/SecLists/mine/subjack_fingerprints.json" -v -w "/home/natsu/Desktop/Tools/myrecon.py/hosts" -o "subto/output" 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: crlf
[*] crlf.py -t 200 -u "/home/natsu/Desktop/Tools/myrecon.py/urls_hosts" 2>&1 >/dev/null &
2020/03/28 07:40:09 open /home/natsu/Desktop/Tools/myrecon.py/hosts: no such file or directory
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: cors
[*] cors.py -t 100 -u "/home/natsu/Desktop/Tools/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: openredirect
[*] openredirect.py -t 100 -u "/home/natsu/Desktop/Tools/myrecon.py/endpoints" 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: xss
[*] xss.py -t 10 -n "/usr/local/bin/phantomjs" -p "/opt/SecLists/mine/xss-myshort.txt" -u "/home/natsu/Desktop/Tools/myrecon.py/endpoints" 2>&1 >/dev/null &
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: smuggling
[*] smuggler.py -v 0 -t 50 -u "/home/natsu/Desktop/Tools/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/natsu/Desktop/Tools/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'
[+] running mod: quickhits
[*] ffuf -u HFUZZ/WFUZZ -w "/home/natsu/Desktop/Tools/myrecon.py/urls":HFUZZ -w "/opt/SecLists/mine/myhardw.txt":WFUZZ -o raw_quickhits 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/natsu/Desktop/Tools/myrecon.py/domains'

I used python3 myrecon.py -d hyatt.com -o hyatt

**Comment by gwen001** [comment]
This is weird. Do you have any file in the hyatt directory ?

**Comment by KathanP19** [comment]
Nope it is created by the tool itself

**Comment by gwen001** [comment]
Could you give me a `ls -lR` please

**Comment by KathanP19** [comment]
┌─[✗]─[natsu@parrot]─[~/Desktop/Tools/myrecon.py]
└──╼ $ls -lR
.:
total 60
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 cors
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 crlf
-rw-r--r-- 1 natsu natsu    0 Mar 30 10:56 endpoints_grabbed
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 googledorks
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 hyatt
drwxr-xr-x 3 natsu natsu 4096 Mar 30 10:50 modules
-rwxr-xr-x 1 natsu natsu 6339 Mar 30 10:51 myrecon.py
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 openredirect
-rw-r--r-- 1 natsu natsu    0 Mar 30 10:56 raw_github-endpoints
-rw-r--r-- 1 natsu natsu    0 Mar 30 10:56 raw_google-domain
-rw-r--r-- 1 natsu natsu   29 Mar 30 10:49 README.md
-rw-r--r-- 1 natsu natsu  644 Mar 30 10:49 report.tpl
-rw-r--r-- 1 natsu natsu   48 Mar 30 10:49 requirements.txt
drwxr-xr-x 5 natsu natsu 4096 Mar 30 10:56 screenshot
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 smuggler
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 subto
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 xss

./cors:
total 0

./crlf:
total 0

./googledorks:
total 0
-rw-r--r-- 1 natsu natsu 0 Mar 30 10:56 output

./hyatt:
total 268
-rw-r--r-- 1 natsu natsu      9 Mar 30 10:55 domains
-rw-r--r-- 1 natsu natsu  21319 Mar 30 10:55 hosts
-rw-r--r-- 1 natsu natsu  19209 Mar 30 10:56 hosts_alive
-rw-r--r-- 1 natsu natsu    182 Mar 30 10:56 hosts_dead
-rw-r--r-- 1 natsu natsu  36250 Mar 30 10:56 hosts_ips
-rw-r--r-- 1 natsu natsu   3441 Mar 30 10:56 ips
-rw-r--r-- 1 natsu natsu  27196 Mar 30 10:56 ips_hosts
-rw-r--r-- 1 natsu natsu 148192 Mar 30 10:56 tmp_hosts

./modules:
total 92
-rw-r--r-- 1 natsu natsu 6379 Mar 30 10:49 app.py
-rw-r--r-- 1 natsu natsu 1324 Mar 30 10:49 cors.py
-rw-r--r-- 1 natsu natsu 1403 Mar 30 10:49 crlf.py
-rw-r--r-- 1 natsu natsu 2184 Mar 30 10:49 endpoints.py
-rw-r--r-- 1 natsu natsu 1712 Mar 30 10:49 extractjuicy.py
-rw-r--r-- 1 natsu natsu 3834 Mar 30 10:49 functions.py
-rw-r--r-- 1 natsu natsu 4479 Mar 30 10:49 googledorks.py
-rw-r--r-- 1 natsu natsu 1500 Mar 30 10:49 openredirect.py
-rw-r--r-- 1 natsu natsu 3181 Mar 30 10:49 portscan.py
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 __pycache__
-rw-r--r-- 1 natsu natsu 2590 Mar 30 10:49 quickhits.py
-rw-r--r-- 1 natsu natsu 2895 Mar 30 10:49 report.py
-rw-r--r-- 1 natsu natsu 2961 Mar 30 10:49 resolve.py
-rw-r--r-- 1 natsu natsu  611 Mar 30 10:49 resume.py
-rw-r--r-- 1 natsu natsu 1435 Mar 30 10:49 screenshot.py
-rw-r--r-- 1 natsu natsu 1497 Mar 30 10:49 smuggling.py
-rw-r--r-- 1 natsu natsu 1746 Mar 30 10:49 subdomains.py
-rw-r--r-- 1 natsu natsu 1798 Mar 30 10:49 subto.py
-rw-r--r-- 1 natsu natsu 1858 Mar 30 10:49 urls.py
-rw-r--r-- 1 natsu natsu 2289 Mar 30 10:49 wayback.py
-rw-r--r-- 1 natsu natsu 1943 Mar 30 10:49 xss.py

./modules/__pycache__:
total 68
-rw-r--r-- 1 natsu natsu 6225 Mar 30 10:50 app.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1245 Mar 30 10:56 cors.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1325 Mar 30 10:56 crlf.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 2017 Mar 30 10:56 endpoints.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 2938 Mar 30 10:50 functions.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 3222 Mar 30 10:56 googledorks.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1373 Mar 30 10:56 openredirect.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 2168 Mar 30 10:56 quickhits.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 2496 Mar 30 10:55 resolve.cpython-37.pyc
-rw-r--r-- 1 natsu natsu  818 Mar 30 10:56 resume.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1375 Mar 30 10:56 screenshot.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1355 Mar 30 10:56 smuggling.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 2052 Mar 30 10:50 subdomains.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1551 Mar 30 10:56 subto.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1998 Mar 30 10:56 urls.cpython-37.pyc
-rw-r--r-- 1 natsu natsu 1575 Mar 30 10:56 xss.cpython-37.pyc

./openredirect:
total 0

./screenshot:
total 12
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 headers
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 html
drwxr-xr-x 2 natsu natsu 4096 Mar 30 10:56 screenshots

./screenshot/headers:
total 0

./screenshot/html:
total 0

./screenshot/screenshots:
total 0

./smuggler:
total 0

./subto:
total 0

./xss:
total 0

**Comment by gwen001** [comment]
Ok I found the bug, I'll try to fix it asap. For now can you do this way:
- create your project directory `mkdir example.com`
- go that directory `cd example.com`
- run the script: `python3 /home/netsu/Desktop/Tools/myrecon.py/myrecon.py -d example.com`

The problem is the `-o` option then the module don't reload properly.

**Comment by gwen001** [comment]
Abandoned project.
