### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [gwen001/myrecon.py#8]
sh: 1: sh: 1: sh: 1: /home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
/home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
/home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
sh: 1: /home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
sh: 1: /home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
sh: 1: /home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
sh: 1: /home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
sh: 1: /home/gdattacker/Desktop/myrecon.py/myrecon.py: not found
sh: 1: /home/gdattacker/Desktop/myrecon.py/myrecon.py: not found

**Comment by gwen001** [comment]
Sorry, abandoned project.

But since many peoples encounter the same problem: all .py must be in your executable path.
